[tool.flakehell]
base = "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/0.16.1/styles/flakehell.toml"

[tool.flakehell.plugins]
flake8-docstrings = [
    "+*",
    # Missing docstring in public module.
    "-D100",
    # Missing docstring in public package.
    "-D104",
    # Missing docstring in __init__
    "-D107",
    # First line should be in imperative mood.
    "-D401",
]
wemake-python-styleguide = [
    "+*",
    
    # Forbids to have names with underscored numbers pattern.
    "-WPS114",
    
    # Forbids to use anything but snake_case for naming class attributes.
    "-WPS115",
    
    # Forbids to use more than one consecutive underscore in variable names.
    "-WPS116",

    # Found `f` string
    "-WPS305",

    # Found class without a base class
    "-WPS306",

    # Found `%` string formatting
    "-WPS323",

    # Found implicit string concatenation
    "-WPS326",

    # Found walrus operator
    "-WPS332",
    
    # Found multiline conditions
    "-WPS337",
]

pycodestyle = [
    "+*",
    # Line break after binary operator.
    "-W504",
]

flake8-rst-docstrings = [
    "-*",
]

darglint = [
    "+*",
    # The docstring parameter type doesn't match function.
    "-DAR103",
    # The docstring parameter type doesn't match function.
    "-DAR203",
]


flake8-quotes = [
    # Remove bad quotes from multiline string
    # We need " quotes in ''' multiline strings to express raw SQL.
    "-Q001",
]

flake8-coding = [
    # Coding magic comment not found
    "-C101",
]


[tool.flakehell.exceptions."tests/"]
flake8-docstrings = [
    # Missing docstring in public function.
    "-D103",
    # Missing docstring in public method.
    "-D102",
]

wemake-python-styleguide = [
    # Forbids to use magic numbers in your code.
    "-WPS432",
    # Found compare with falsy constant.
    "-WPS520",
    # Found outer scope names shadowing: {0}.
    "-WPS442",
    # Found string constant over-use.
    "-WPS226",
    # Found overused expression:
    "-WPS204",
    # Found too many `assert` statements:
    "-WPS218",
]

flake8-bandit = [
    # Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
    "-S101",
]


[tool.flakehell.exceptions."**/__init__.py"]
pyflakes = [
    # %s imported but unused
    # In __init__.py files, we often have to import things just to make them easily importable from other packages.
    "-F401",
]

[tool.flakehell.exceptions."**/settings.py"]
wemake-python-styleguide = [
    # Found mutable module constant
    "-WPS407",
]

